name: Build and Deploy via Terraform

on:
  push:
# branches: [main]


env:
  PROJECT_ID: goldigger-460505
  REGION: europe-west12
  SERVICE_NAME: nextjs-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v3

      - name: Set up GCP auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="commit_sha=$TAG"
        env:
          TF_VAR_mongodb_atlas_public_key: ${{ secrets.TF_VAR_mongodb_atlas_public_key }}
          TF_VAR_mongodb_atlas_private_key: ${{ secrets.TF_VAR_mongodb_atlas_private_key }}
          TF_VAR_atlas_org_id: ${{ secrets.TF_VAR_atlas_org_id }}
          TF_VAR_database_url: ${{ secrets.TF_VAR_database_url }}
          TF_VAR_atlas_project: ${{ secrets.TF_VAR_atlas_project }}
          TF_VAR_atals_app_user: ${{ secrets.TF_VAR_atlas_app_user }}
          TF_VAR_atlas_app_password: ${{ secrets.TF_VAR_atlas_app_password }}
          TF_VAR_atlas_db_name: ${{ secrets.TF_VAR_atlas_db_name }}
          TF_VAR_artifact_service_account: ${{ secrets.TF_VAR_artifact_service_account }}
