name: Build and Deploy via Terraform

on:
  push:
    branches: [main]

env:
  PROJECT_ID: goldigger-460505
  REGION: europe-west12
  SERVICE_NAME: nextjs-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v3

      - name: Set up GCP auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker auth for GCR
        run: gcloud auth configure-docker

      - name: Set image tag
        id: tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$TAG .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=$TAG"
        env:
          TF_VAR_project_id: ${{ env.PROJECT_ID }}
          TF_VAR_region: ${{ env.REGION }}
          TF_VAR_mongodb_atlas_public_key: ${{ secrets.TF_VAR_mongodb_atlas_public_key }}
          TF_VAR_mongodb_atlas_private_key: ${{ secrets.TF_VAR_mongodb_atlas_private_key }}
          TF_VAR_atlas_org_id: ${{ secrets.TF_VAR_atlas_org_id }}
          TF_VAR_atlas_project_id: ${{ secrets.TF_VAR_atlas_project_id }}
